version: '2'
services:
    styleguide:
        image: node:9.2
        ports:
            - 4000:4000
        volumes:
            - ./services/frontend/client:/usr/src/app
        working_dir: /usr/src/app
        entrypoint: ["yarn", "run:styleguide"]
