version: '2'
services:
    client:
        image: node:9.2
        ports:
            - 3000:3000
        volumes:
            - ./services/frontend/client:/usr/src/app
        working_dir: /usr/src/app
        entrypoint: ["yarn", "run:dev"]
