version: '2'
services:
    postgres:
        image: postgres:9.6
        ports:
            - ${PG_PORT}:5432
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DATABASE}
        volumes:
            - ${HUMBLE_DATA}/pg:/var/lib/postgresql/data
            - ${HUMBLE_DATA}/backup:/backup
        restart: always
